apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codex-proxy-data
  namespace: codex-proxy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-wffc
  resources:
    requests:
      storage: 1Gi
